#!/usr/bin/env bash
# install a nginx server and runs

sudo apt-get update
sudo apt-get -y install nginx
# allow port 80
sudo ufw allow 'Nginx HTTP'
# content html
echo "Holberton School" > sudo /var/www/index.html
sudo systemctl start nginx
