#!/usr/bin/env bash
# install a nginx server and runs

sudo apt-get update
sudo apt-get -y install nginx
# allow port 80
sudo ufw allow 'Nginx HTTP'
# content html
echo "Holberton School" > /var/www/html/index.html
sudo /etc/init.d/nginx start
