#!/usr/bin/env bash
# redirect a page with 301 Moved Permanently and create a custom 404 page

sudo apt-get update
sudo apt-get -y install nginx
# Firewall port 80
sudo ufw allow 'Nginx HTTP'
# Index file and start
echo "Holberton School" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sed -i '/listen 80 default_server/a error_page 404 /custom_404.html; location= /custom_404.html {root /usr/share/nginx/html; \ninternal;}' /etc/nginx/sites-available/default
sudo service nginx restart
