#!/usr/bin/env bash
# Set HAproxy

apt-get update
apt-get -y install haproxy
echo "ENABLED=1" >> /etc/default/haproxy

echo $'\nfrontend http-front\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 1239-web-01 35.190.146.135:80 check\n\tserver 1239-web-02 35.185.29.47:80 check' >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
