#!/usr/bin/env bash
# Task number 1 in only 7 lines
sed -i "s/#user www-data;/ user nginx;/g" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sed -i "s/Listen 8080/#Listen 8080/g" /etc/apache2/ports.conf
pkill -1 apache2
chmod a+wrx /etc/nginx/nginx.conf /etc/apache2/ports.conf | sudo -u nginx service nginx restart
